### ISSUE TITLE
nexeで固めた時にnode_modulesフォルダもないと起動しなくなる。

### ISSUE THREAD

**Issue by ginpaydo** [ginpaydo/ToricchiSecondSeason#3]
Error: The specified module could not be found.
\\?\C:\Users\ginpay\Desktop\aaaa\node_modules\sqlite3\lib\binding\node-v64-win32-x64\node_sqlite3.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\ginpay\Desktop\aaaa\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
PS C:\Users\ginpay\Desktop\aaaa>

**Comment by ginpaydo** [comment]
どうやら現在の所Node.jsでSQLiteは使わない方が良いみたい。
c++ビルドが必要で、しかも実行環境に合わせる必要があるので配布が無理。

SQLite以外を使用するように変更する。

**Comment by ginpaydo** [comment]
Webpackの場合も同様。SQLite3はパックできないので配布が困難。
純JSのライブラリを使う手もあるが、ORMが使えなくなる。
Node.jsでSQLiteは避けた方が良い。

.NET Coreとかならどうだろうか？
